### PR TITLE
ad nonswad gentx

### PR DESCRIPTION
**Pull request by nonswad**
add nonswad.json gentx

### CODE REVIEW

**Comment by EG-easy** [comment]
@nonswad You submit wrong format json file.

**Comment by EG-easy** [comment]
Hi, @nonswad can you remove old json from PR to pass the test?

**Comment by nonswad** [comment]
is it ok now? Or should I 1 of 2 remaining PRs?

**Comment by EG-easy** [comment]
Thank you for updating!

**Pull request merged**
