### PR TITLE
Create gagarin.js 

### PR DESCRIPTION
**Pull request by dmbqh**

### CODE REVIEW

**Comment by dmbqh** [comment]
reject it please )

**Comment by dmbqh** [comment]
Rename the key please to gagarin.js..... sorry, i've missed the extension (((

**Comment by EG-easy** [comment]
@dmbqh Hi, can you put .json at the end of file and remove one of the gentx ?

**Comment by dmbqh** [comment]
Hi, Done. Please Check )))

Thanx a lot

**Pull request closed without merging**
