### PR TITLE
Add Appload

### PR DESCRIPTION
**Pull request by rozum-dev**

### CODE REVIEW

**Comment by EG-easy** [comment]
@rozum-dev your gentx is something wrong. Please update it.
Maybe chain-id or denom is incorrect when producing gentx.

**Comment by rozum-dev** [comment]
Appload tx updated pls check if it ok now

**Comment by EG-easy** [comment]
@rozum-dev Hi, can you delete old gentx ? It prevent from passing test.

**Comment by rozum-dev** [comment]
Deleted

**Comment by EG-easy** [comment]
Ummm it seems your gentx is something wrong. The workflow test is not passed.

**Comment by EG-easy** [comment]
Thank you for updating!

**Pull request merged**
