### PR TITLE
lxsslnode.json

### PR DESCRIPTION
**Pull request by lxssl**

### CODE REVIEW

**Comment by lxssl** [comment]
Please check correct "lxsslnode.json" filename.
"lxsslnod.json" is errorous filename( correct one is "lxsslnode.json", moniker = lxsslnode

**Comment by EG-easy** [comment]
@lxssl Hi, can you delete unused gentx ?

**Comment by lxssl** [comment]
> @lxssl Hi, can you delete unused gentx ?
@EG-easy I would love to, but can't find how yet, sorry)

**Comment by EG-easy** [comment]
Now genesis.json is released and I will close this PR. You can join after testnet launch. Thanks.

**Pull request closed without merging**
